# Generated by Django 5.1.1 on 2024-09-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supports', models.TextField()),
                ('business_type', models.CharField(max_length=300)),
                ('portal_link', models.URLField()),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='CorporateInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_number', models.CharField(max_length=50)),
                ('incorporation_date', models.CharField(max_length=50)),
                ('registration_date', models.CharField(max_length=50)),
                ('company_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('registered_address', models.TextField()),
                ('business_address', models.TextField()),
                ('nature_of_business', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('registration_no', models.CharField(max_length=50)),
                ('ic_passport_no', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('designation', models.CharField(max_length=100)),
                ('appointment_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('feedback_type', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('sentiment', models.CharField(default='Positive', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('non_current_assets', models.CharField(max_length=100)),
                ('current_assets', models.CharField(max_length=100)),
                ('non_current_liabilities', models.CharField(max_length=100)),
                ('current_liabilities', models.CharField(max_length=100)),
                ('share_capital', models.CharField(max_length=100)),
                ('retained_earnings', models.CharField(max_length=100)),
                ('revenue', models.CharField(max_length=100)),
                ('profit_before_tax', models.CharField(max_length=100)),
                ('profit_after_tax', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_no', models.CharField(max_length=100)),
                ('business_address', models.TextField()),
                ('nature_of_business', models.TextField()),
                ('total_issued', models.CharField(max_length=100)),
                ('registrar_of_companies', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('total_issued', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shareholders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('ic_passport_no', models.CharField(max_length=50)),
                ('total_shares', models.IntegerField()),
            ],
        ),
    ]
