# Generated by Django 5.1.1 on 2024-09-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysupportapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
