# Generated by Django 5.1.1 on 2024-09-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysupportapp', '0002_usermanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanual',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manual_images/'),
        ),
    ]
